name: Main
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Run build script
        run: yarn build

      - name: Upload build artifacts
        uses: actions/cache@v3
        with:
          path: ./packages
          key: ${{ runner.os }}-build-${{ github.sha }}

  test:
    name: Test
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Download build artifacts
        uses: actions/cache/restore@v3
        with:
          path: ./packages
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Install project dependencies
        run: yarn install

      - name: Run tests
        run: yarn test --coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Download build artifacts
        uses: actions/cache/restore@v3
        with:
          path: ./packages
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Install project dependencies
        run: yarn install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
