name: Pull Request
on:
  pull_request:
    types: [opened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Run build script
        run: yarn build

      - name: Upload build artifacts
        uses: actions/cache@v3
        with:
          name: packages
          path: ./packages

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Download build artifacts
        uses: actions/cache/restore@v3
        with:
          name: packages
          path: ./packages

      - name: Install project dependencies
        run: yarn install

      - name: Run tests
        run: yarn test --coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
